### ISSUE TITLE
Missing config option

### ISSUE THREAD

**Issue by minhh2792** [PixelStudiosDev/BedWars1058-Ultimate#1]
https://github.com/CubeCrafter/BedWars1058-Ultimate/blob/92b703abaa998a388458f6742f8461ef8b1c2235/src/main/java/me/cubecrafter/ultimate/listeners/BuilderListener.java

"You have run out of wool" is not configurable, please double check all of the plugin messages

**Comment by leo18bernese** [comment]
Done
