### ISSUE TITLE
Builder issues

### ISSUE THREAD

**Issue by PixelEast** [PixelStudiosDev/BedWars1058-Ultimate#3]
1. Builder sometimes automatically changes buildtool modes after using ultimate item, this will cause me to suddenly build a wall while continuously using the bridge

2. The message text of some builder cannot be translated
![0{H2Y9_B}E}TZ_NG25D48 Q](https://github.com/CubeCrafter/BedWars1058-Ultimate/assets/30312760/9453877d-41b4-4380-9128-08b7207e6760)
![KGCXE3U P$G$T0P6BO(H0D1](https://github.com/CubeCrafter/BedWars1058-Ultimate/assets/30312760/28463a00-e736-4f3c-8ed4-f75a0b52f5e7)

**Comment by CubeCrafter72** [comment]
fixed in the next update
