### ISSUE TITLE
Kangaroo issues

### ISSUE THREAD

**Issue by PixelEast** [PixelStudiosDev/BedWars1058-Ultimate#6]
1. After the kangaroo is killed, the killer can obtain all the resource carried by him, but after rebirth, the kangaroo's ability will reserve resources for him, so there will be double the amount of resources

2 Kangaroos should retain half of the resource they carry after rebirth, not all of them. 
During testing, I found that their resource are strangely retained, sometimes all of them are retained, and sometimes only 4/1 are losting

**Comment by CubeCrafter72** [comment]
fixed in the next update
