### ISSUE TITLE
Game mechanism issues

### ISSUE THREAD

**Issue by PixelEast** [PixelStudiosDev/BedWars1058-Ultimate#7]
1. After the game is over, the ultimates selected by the player will not be cleared. These ultimates will still be selected after they join the next game, I think it's shoud to clear the selected ultimates after each game is end

2. In respawn and spectate mode, you can still use the selected superpowers, such as kangaroo's double jump

3. When a player is final killed by Void, their's ultimate items will be dropped to the kill-drops-loc position

**Comment by CubeCrafter72** [comment]
fixed in the next update
